version: '3'

services:

  memcached:
    image: memcached
    restart: always
    expose:
      - "11211"
    networks:
      default:
        aliases:
          - memcached

  dbmaster:
    build: ./containers/mysql     
    image: local-mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    privileged: true
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dbmaster:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    networks:
      default:
        aliases:
          - dbmaster

  nextcloud:
    build: ./containers/nextcloud
    image: local-nextcloud
    privileged: true
    restart: always
    ports:
      - 80:80
    environment:
      - MC_HOST=memcached
      - MYSQL_HOST=dbmaster
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - S3_BUCKET
      - S3_KEY
      - S3_SECRET
      - S3_REGION
      # - NEXTCLOUD_ADMIN_USER
      # - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS
    depends_on:
      - memcached
      - dbmaster
    volumes:
      - ./data:/var/www/html
    networks:
      default:
        aliases:
          - nextcloud

  # web:
  #   build: ./containers/nginx
  #   image: local-nginx
  #   ports:
  #     - 80:80
  #     # - 443:443
  #   volumes:
  #     - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./containers/nginx/nextcloud.conf:/etc/nginx/conf.d/nextcloud.conf:ro
  #     - nextcloud:/var/www/html
  #   depends_on:
  #     - nextcloud
  #   restart: always
  #   networks:
  #     default:
  #       aliases:
  #         - web

volumes: 
  nextcloud:
  dbmaster:

networks:
  default: